### ISSUE TITLE
Can you help 

### ISSUE THREAD

**Issue by ARR4NN** [JamesHawkinss/movie-web#16]
Can you dm me on discord i need help making pull requests **ARR4NN#0340**

**Comment by JamesHawkinss** [comment]
I'm not able to assist you in making a pull request, sorry.

Your "main" branch is not mergeable into my "master" branch because you basically copy/pasted the files from one branch to another. It's not based on master.

If you want to resolve this, I recommend either:

 - Deleting your fork entirely, and remaking it. 
 - Ignore the "main" branch and begin writing code to master.
 
 Google is your friend when it comes to basic git.
